safe: true
lsi: false
markdown: redcarpet
pygments: false
exclude:
- README
days:
{{#each days}}- {{ this }}
{{/each}}
locations:
{{#each locations}}-
  filename: {{ filename }}
  name: {{ name }}
{{/each}}
